name: build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1
    - uses: php-actions/phpunit@v1
    - run: composer install
    - run: phpunit tests/
