name: build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Run tests
        run: ./vendor/bin/phpunit ./tests

  benchmarks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - name: Run benchmarks
        run: php ./bench.php 10000 50000 100000 500000 1000000
