name: build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        uses: actions/checkout@v2
        uses: php-actions/composer@v1
        uses: php-actions/phpunit@v1
        with:
            config: ./phpunit.xml
